name: mstand
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.23.0
  cloud_firestore: ^3.4.9
  firebase_auth: ^3.10.0
  crypto: ^3.0.2
  email_validator: '^2.1.16'
  intl_phone_number_input: ^0.7.1
  email_auth: ^1.0.0
  shared_preferences: ^2.0.15
  introduction_screen: ^3.0.2
  flutter_animator: ^3.2.2
  country_codes: ^2.2.0
  pinput: ^2.2.12
  http: ^0.13.5
  intl: ^0.17.0
  firebase_messaging: ^13.0.4
  url_launcher: ^6.1.6
  awesome_notifications: ^0.6.21
  shimmer: ^2.0.0
  timezone: ^0.9.0
  file_picker: ^5.2.0+1
  firebase_storage: ^10.3.10
  cunning_document_scanner: ^1.1.0
  syncfusion_flutter_calendar: ^20.3.49
  syncfusion_flutter_charts: ^20.3.52
  syncfusion_localizations: ^20.3.49
  syncfusion_flutter_pdfviewer: ^20.3.49
  flutter_downloader: ^1.8.4
  path_provider: ^2.0.11
  device_info_plus: ^6.0.0
  permission_handler: ^10.1.0
  share_plus: ^4.5.3
  photo_view: ^0.14.0
  whatsapp_share2:
  flutter_swipe_action_cell: ^3.0.4
  flutter_native_splash: ^2.2.11
  hawk_fab_menu: ^1.2.0
  fluttertoast: ^8.1.1
  rename: ^2.0.1
  in_app_purchase: ^3.0.8
  in_app_purchase_storekit: ^0.3.2+2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  # flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/bb_logo.png"

# flutter_launcher_name:
#   name: "business_bag"


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/intro_images/
    - assets/login_logo/
    - assets/logos/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
